baseURL = "https://shaddy.dev/"
languageCode = "en-us"
title = "Shaddy's"
theme = "SimpleIntro"

[params]
    mainbg = "https://www.publicdomainpictures.net/pictures/40000/velka/dark-background.jpg"
    name = "Shaddy"
    mainTitle = "Shaddy's"
    mainText = "Welcome to my semi stock site"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"